### ISSUE TITLE
Rename to torchsummary++?

### ISSUE THREAD

**Issue by andrewjong** [TylerYep/torchinfo#17]
This version is much superior to the original version. Love it. Thoughts on differentiating the name so people can find it? Else people think "torchsummary" means the original version.

**Comment by TylerYep** [comment]
Thank you for the kind words! 👍 

I'm certainly open to changing the name, so open to any ideas. I kept the original name because this project was intended as a fork of the original, but ended up evolving quite a bit. The two versions are now incompatible, so I don't think we'll be able to combine the two projects after all, but hopefully this version still has a lot of room to grow.

Probably not torchsummary++ though, since I don't think we can use "+" in PyPI packages and the operator ++ doesn't exist in Python :)

**Comment by andrewjong** [comment]
Brainstorming, alphabetical:
- torch-elucidate
- torch-essence
- torch-express
- torch-exhibit
- torch-display
- torch-gist
- torch-illustrate
- torch-manifest
- torch-present
- torch-seer
- torch-show
- torch-outline

**Comment by TylerYep** [comment]
I was thinking `torchinfo`! But I think this name-change should happen a bit later - there are a few breaking changes I want/ will want to introduce, and switching the name should coincide with those changes.

**Comment by andrewjong** [comment]
I love `torchinfo` :)

**Comment by TylerYep** [comment]
Renamed to `torchinfo`! Thank you for the suggestion.
